AuctionsBucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.AuctionsBucket.name}
    LifecycleConfiguration:     # After liftcycle the data in S3 will be deleted
      Rules:
        - Id: ExpirePictures
          Status: Enabled
          ExpirationInDays: 30

# The public access permission
AuctionsBucketPolicy:
  Type: AWS::S3::BucketPolicy
  Properties:
    Bucket: !Ref AuctionsBucket
    PolicyDocument:
      Statement:
        - Sid: PublicRead   # read only for public 
          Effect: Allow
          Principal: '*'
          Action:
            - s3:GetObject
          Resource: arn:aws:s3:::${self:custom.AuctionsBucket.name}/*